galax_rtx_3070: 
  name: "Placa de Vídeo GALAX - GeForce RTX 3070, 1-Click OC, 8GB GDDR6, DLSS, LHR, Ray Tracing"
  urls:
    - https://www.amazon.com.br/Placa-V%C3%ADdeo-GALAX-GeForce-1-Click/dp/B09KC8B966/ref=sr_1_4?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=37IKGAVQZFPOM&keywords=RTX+3070&qid=1650572920&sprefix=rtx+307%2Caps%2C533&sr=8-4&ufe=app_do%3Aamzn1.fos.25548f35-0de7-44b3-b28e-0f56f3f96147
    - https://www.kabum.com.br/produto/229411/placa-de-video-galax-nvidia-geforce-rtx-3070-1-click-oc-8gb-gddr6-dlss-lhr-ray-tracing-preto-37nsl6md2kch
